### PR TITLE
Refactor + support redirects

### PR DESCRIPTION
**Pull request by matteius**
I refactored this because of a bug I found where if the remote address is not set on the request it will short circuit the user agent check.   I also wanted to be able to redirect to a known URL rather than just return a 400 error, additionally I decided to make the http status code also configurable.  

 Added new tests cases including one to address the issue that fails on the existing trunk--when the remote address is not present on the request and we want to ensure the user agent is checked.

### CODE REVIEW

**Comment by matteius** [comment]
@erikr I have adjusted my PR based on the CI feedback to maintain 100% test coverage.  I also  pinned the versions at less than Django 1.9 in order to support Python 3.3.x
I recommend we remove the CI for Python 2.6.x since as of Django 1.7 Python 2.6.x is not support (requires 2.7.x) and we wouldn't want to pin this library to Django 1.6.x which isn't getting security updates and most people have upgraded past it.

**Comment by matteius** [comment]
The only reason the Python 2.6 build is failing is because we actually import a django feature now that requires Python 2.7

**Comment by erikr** [comment]
I just merged a commit to limit is to Django 1.8 and 1.9 and Python 2.7 and 3.4. Could you rebase on top of that?

**Comment by erikr** [comment]
Other than that, it looks good to me, thanks!

**Comment by erikr** [comment]
Oh, actually I notice there is one part missing: there is no documentation for the new features yet. Could you add them?

**Comment by matteius** [comment]
@erikr I think this should be all set now, let me know if you need something else!

**Comment by erikr** [comment]
Awesome, thanks. If you could also have another look/rebase at #2, we can get that merged and I can roll a new release.

**Comment by erikr** [comment]
It's released! 0.1.3.1 :)

**Pull request merged**
